### ISSUE TITLE
Milestone for first release

### ISSUE THREAD

**Issue by nickaguilarh** [arietimmerman/laravel-openid-connect-server#1]
Hey there, 
I really love the idea of using OIC on laravel. I was going to do an implementation for a project but got into this package and would like to help in the procress. 

I think it would be really good if we can create a milestone, so other people can help to and get an overview of how it's going. 

Greetings, and thanks for this great initiative.

**Comment by arietimmerman** [comment]
Thanks for reaching out. It would be great if you could help.

For me a milestone would be to pass (parts of) the OpenID Connect certification. It should already pass most of the tests for the Authorization Code grant. See https://openid.net/certification/instructions/

What do you think about this?

**Comment by nickaguilarh** [comment]
Great,
I'll start checking that this weekend.
PS: I'll close this
