### ISSUE TITLE
Support Laravel Passport v11

### ISSUE THREAD

**Issue by gorets** [arietimmerman/laravel-openid-connect-server#19]
I try to install this package to Laravel v9.32.0 & Laravel Passport v11.2.0 and I have error

`nl.idaas/laravel-openid-connect v0.2.7 requires laravel/passport ^10 -> found laravel/passport[v10.0.0, ..., 10.x-dev] but it conflicts with your root composer.json require (^11.2).`

**Comment by arietimmerman** [comment]
I have started working on adding support, hoping I could update the package to support both v10 and v11, but seems that there are a few breaking changes. Now I am in doubt whether I'll update everything and drop support for Passport v10, or support both versions with two versions of  this package.
Probably I'll just drop support for v10 as I need to upgrade my own software (https://www.idaas.nl/) to Laravel v9.32 / Passport v11 as well.

**Comment by georgeboot** [comment]
Any progress on this? Any specific things I can do to assist?

**Comment by arietimmerman** [comment]
No progress yet. If you are willing to work on introducing support for Passport v11 that would be great.
I am quite sure it will be difficult to remain backwards compatibility. If that turns out to be the case, it's OK to introduce >v11 only.

**Comment by wq9578** [comment]
Same problem here when trying to upgrade to Laravel 10 requiring Laravel passport 11:
```
$ composer update -W
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nl.idaas/laravel-openid-connect ^0.2.7 -> satisfiable by nl.idaas/laravel-openid-connect[v0.2.7, v0.2.8].
    - nl.idaas/laravel-openid-connect[v0.2.7, ..., v0.2.8] require laravel/passport ^10 -> found laravel/passport[v10.0.0, ..., v10.4.2] but it conflicts with your root composer.json require (^11.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by omitobi** [comment]
@wq9578 now the package supports laravel 10 and passport 11
